package:
  name: pines
  version: "2.8"

source:
  git_rev: v2.8
  git_url: https://github.com/jpn--/pines.git

requirements:
  build:
    - python>=3.6
    - setuptools
  run:
    - python>=3.6

test:
  imports:
    - pines

about:
  home: https://github.com/jpn--/pines
  license: MIT
  license_file: LICENSE