package:
  name: pines
  version: "2.84.0"

source:
  git_rev: v2.84.0
  git_url: https://github.com/jpn--/pines.git

requirements:
  build:
    - python >=3.6
    - setuptools
    - distributed >=1.17.1
    - dask >=0.15
    - pandas >=0.20.3
    - aenum
    - dbf >=0.96
    - egnyte >=0.5.3
    - numpy >=1.13.1
    - scipy >=0.19.1
    - pytables >=3.4.2
    - mysql-connector-python >=2.0.4
  run:
    - python >=3.6
    - distributed >=1.17.1
    - dask >=0.15
    - pandas >=0.20.3
    - aenum
    - dbf >=0.96
    - egnyte >=0.5.3
    - numpy >=1.13.1
    - scipy >=0.19.1
    - pytables >=3.4.2
    - mysql-connector-python >=2.0.4

test:
  imports:
    - pines

about:
  home: https://github.com/jpn--/pines
  license: MIT
  license_file: LICENSE